// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "Postgres knows nothing about.Net's StringComparison, LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Landing.Domain.DictionaryService.GetDepartmentsAsync(Synergy.Common.Domain.Models.Common.SearchArgsModel,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Synergy.Common.Domain.Models.Common.SearchResultModel{Synergy.Common.Domain.Models.Common.FastEntityModel{System.Int32}}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "Postgres knows nothing about.Net's StringComparison, LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Landing.Domain.DictionaryService.GetCountiesAsync(Synergy.Common.Domain.Models.Common.SearchArgsModel{Synergy.Landing.Models.CountySearchArgs,Synergy.Landing.Models.CountySortField},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Synergy.Common.Domain.Models.Common.SearchResultModel{Synergy.Common.Domain.Models.Common.FastEntityModel{System.Int32}}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "Postgres knows nothing about.Net's StringComparison, LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Landing.Domain.DictionaryService.GetStateListAsync(Synergy.Common.Domain.Models.Common.SearchArgsModel,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Synergy.Common.Domain.Models.Common.SearchResultModel{Synergy.Common.Domain.Models.Common.FastEntityModel{System.Int32}}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "Postgres knows nothing about.Net's CultureInfo, LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Landing.Domain.DictionaryService.GetCountiesAsync(Synergy.Common.Domain.Models.Common.SearchArgsModel{Synergy.Landing.Models.CountySearchArgs,Synergy.Landing.Models.CountySortField},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Synergy.Common.Domain.Models.Common.SearchResultModel{Synergy.Common.Domain.Models.Common.FastEntityModel{System.Int32}}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "Postgres knows nothing about.Net's StringComparison, LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Landing.Domain.DictionaryService.GetCountiesAsync(Synergy.Common.Domain.Models.Common.SearchArgsModel{Synergy.Landing.Models.Dictionary.CountySearchArgs,Synergy.Landing.Models.Dictionary.CountySortField},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Synergy.Common.Domain.Models.Common.SearchResultModel{Synergy.Common.Domain.Models.Common.FastEntityModel{System.Int32}}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "Postgres knows nothing about.Net's CultureInfo, LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Landing.Domain.DictionaryService.GetCountiesAsync(Synergy.Common.Domain.Models.Common.SearchArgsModel{Synergy.Landing.Models.Dictionary.CountySearchArgs,Synergy.Landing.Models.Dictionary.CountySortField},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Synergy.Common.Domain.Models.Common.SearchResultModel{Synergy.Common.Domain.Models.Common.FastEntityModel{System.Int32}}}")]
